sagiterre_core_news:
    path:     /
    defaults: { _controller: SAGITERRECoreBundle:Core:news }

sagiterre_core_news_add:
    path:     /ajouter-une-news
    defaults: { _controller: SAGITERRENewsBundle:News:add }