sagiterre_layout_WM_form:
    path:     /welcomeMessageForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyWelcomeMessage, id: 0 }
    options:
            expose: true

sagiterre_layout_ST_form:
    path:     /sectionTwoForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifySectionTwo, id: 0 }
    options:
            expose: true

sagiterre_layout_STHO_form:
    path:     /sectionThreeOneForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifySectionThreeOne, id: 0 }
    options:
            expose: true

sagiterre_layout_STHT_form:
    path:     /sectionThreeTwoForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifySectionThreeTwo, id: 0 }
    options:
            expose: true

sagiterre_layout_STHTH_form:
    path:     /sectionThreeThreeForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifySectionThreeThree, id: 0 }
    options:
            expose: true

sagiterre_layout_SF_form:
    path:     /sectionFourForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifySectionFour, id: 0 }
    options:
            expose: true

sagiterre_layout_SFI_form:
    path:     /sectionFiveForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifySectionFive, id: 0 }
    options:
            expose: true

sagiterre_layout_about_form:
    path:     /aboutForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyAbout, id: 0 }
    options:
            expose: true

sagiterre_layout_team_form:
    path:     /teamForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyTeam, id: 0 }
    options:
            expose: true

sagiterre_layout_mission_form:
    path:     /missionForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyMission, id: 0 }
    options:
            expose: true

sagiterre_layout_activities_form:
    path:     /activitiesForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyActivities, id: 0 }
    options:
            expose: true

sagiterre_layout_otheractivities_form:
    path:     /otheractivitiesForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyOtherActivities, id: 0 }
    options:
            expose: true

sagiterre_layout_contact_form:
    path:     /contactForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyContact, id: 0 }
    options:
            expose: true

sagiterre_layout_news_form:
    path:     /newsForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyNews, id: 0 }
    options:
            expose: true

sagiterre_layout_newsarchives_form:
    path:     /newsArchivesForm/{id}/{part}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:modifyNewsArchives, id: 0 }
    options:
            expose: true

sagiterre_layout_deactivate_horse:
    path:     /deactivateHorse/{id}
    defaults: { _controller: SAGITERRELayoutBundle:Layout:deactivateHorse, id: 0 }
    options:
            expose: true