<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * NewsArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
