<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * OtherActivitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherActivitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
