<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SectionThreeThreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionThreeThreeRepository extends \Doctrine\ORM\EntityRepository
{
}
