<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SectionThreeOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionThreeOneRepository extends \Doctrine\ORM\EntityRepository
{
}
