<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SectionTwoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionTwoListRepository extends \Doctrine\ORM\EntityRepository
{
}
