<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SectionThreeTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionThreeTwoRepository extends \Doctrine\ORM\EntityRepository
{
}
