<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SectionFourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionFourRepository extends \Doctrine\ORM\EntityRepository
{
}
