<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SectionFiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionFiveRepository extends \Doctrine\ORM\EntityRepository
{
}
