<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * SlideImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideImageRepository extends \Doctrine\ORM\EntityRepository
{
}
