<?php

namespace SAGITERRE\LayoutBundle\Repository;

/**
 * TeamListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamListRepository extends \Doctrine\ORM\EntityRepository
{
}
